# app.yaml - For App Engine deployment
runtime: python312

env_variables:
  PVWATTS_API_KEY: "7NIcgO78r1a3xv4RKzWchNyYB0hlLrCNOek6Rv28"
  SECRET_KEY: "47dd90932b6d56768d42fdb6b96c5c0f8d4dc5a4f890deab460b5f6d6084519f"

# Minimal scaling - scale to zero when not in use
automatic_scaling:
  min_instances: 0  # Scale to zero to minimize costs
  max_instances: 3  # Keep low for development
  target_cpu_utilization: 0.8
  min_pending_latency: "3s"  # Allow some latency to reduce instances

# Minimal resources - smallest available
resources:
  cpu: 1
  memory_gb: 0.5  # Minimum memory

# Static file handling
handlers:
- url: /static
  static_dir: static
  secure: always
  expiration: "1h"

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

# Session security is handled in Flask app configuration
